### ISSUE TITLE
nao funciona

### ISSUE THREAD

**Issue by habzeRO-sys** [MarcoCuel/hFansite#1]
Cara ñ funciona por completo, login, resgistro, ñ muda avatar dos user e paginas quebradas. pena pq e um bom projeto

**Comment by MarcoCuel** [comment]
Sim o projeto não está finalizado, pois eu fiz tudo em apenas um fim de semana, e até agora não consegui tempo para terminar o mesmo, liberei apenas pra quem quisesse testar e talz, em relação ao login/registro e avatar eu indicaria o uso de plugins para isso. Para o avatar eu indico o https://br.wordpress.org/plugins/wp-user-avatar/
Já plugin para registro existem vários, eu testei alguns, mas não lembro de nenhum que eu achei legal. Teria que instalar e testar pra ver qual se encaixa melhor no que você vai usar. A maioria tem opção de personalizar os campos e tudo mais.

Eu ainda pretendo fazer um plugin único para tudo isso, porem no momento eu não tenho nem ideia de quando terei tempo para fazer isso.

**Comment by habzeRO-sys** [comment]
Certo, valeu. Sucesso!
